x-db-env: &db-env
  DATABASE_URL: ${DATABASE_URL:-mongodb://mongo:27017/parking-management}

services:
  db:
    profiles: ["localdb"]
    image: mongo:6-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: parking-management
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - parking-management

volumes:
  mongo_data: null
networks:
  parking-management:
    driver: bridge
    name: parking-management
